use_frameworks!

platform :ios, '8.0'

target 'HZNetworking_Example' do
  pod 'HZNetworking', :path => '../'

  target 'HZNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
